### ISSUE TITLE
Full Supabase stack on the cloud

### ISSUE THREAD

**Issue by organicnz** [daniellaera/supabase-react-auth#11]
Awesome tutorial mate. Thank you very much for sharing :) 

Apologies, that writing here as I couldn't leave this message on YT for some odds 😅 

We are also developing our food sharing application based on React & Supabase. You mentioned that you previously used the Supabase stack locally. I was just wondering, did you happen to post this code in a repo? I think we're reaching the limit of what Supabase can provide for free, and I'd like to be ready to run it on the DigitalOcean cloud :) 

Kind regards,
Tarlan Isaev

**Comment by daniellaera** [comment]
hello @organicnz and thanks a lot for your feedback, it's ok for the topic here ;)
It's probably a misunderstanding, but no, I don't use Supabase locally, what I actually use for local development is simply my Postgres in a Docker container and then I switch to my Supabase service. But I could of course adopt the local version of Supabase. Do you need help on that, because I could maybe provide/prepare a tutorial onhow to use Supabase local and find a way to deploy somewhere in the cloud?

**Comment by organicnz** [comment]
> 

Hi Dan, 

Thank you very much for your reply :)

Oops my appologies I didn't get it right. Yeah, it would be very nice and helpful if you could provide/prepare such tutorial, mate for DigitalOcean. It sounds more like a feature request not an issue ahah :)

**Comment by organicnz** [comment]
Hey Dan,

Sorry for asking. Could you pls also share your excalidraw draft by any chance? I'd like to show to my small dev team :)

**Comment by daniellaera** [comment]
done, added in the repo description https://github.com/daniellaera/supabase-react-auth
